name: CI | Conventions

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  pull-request-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Install Cocogitto
        uses: cocogitto/cocogitto-action@390bda87a19bf627e03ad075c67a11e9ddbb7547
        with:
          command: --version

      - name: Validate PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: cog verify "$PR_TITLE"
